# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mdm-proj2-docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mdmproj2container.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dc7ab74954ab422986b33ca5d659e556 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_94bb68c1c30a4df69acef1ab40887bc2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mdmproj2container.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dc7ab74954ab422986b33ca5d659e556 }}/mdm_proj2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mdm-proj2-docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_159f767c95da455984f4d0df03886d40 }}
        images: 'mdmproj2container.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dc7ab74954ab422986b33ca5d659e556 }}/mdm_proj2:${{ github.sha }}'